name: ohmywrt-direct-proxy

services:
  direct-proxy:
    image: ${DIRECT_PROXY_IMAGE}
    container_name: ohmywrt-direct-proxy
    entrypoint: ["/usr/local/bin/sing-box"]
    command: ["run", "-c", "/etc/sing-box/config.json"]
    ports:
      - "${DIRECT_PROXY_BIND_ADDRESS}:${DIRECT_PROXY_PORT}:7890"
    volumes:
      - ./sing-box:/usr/local/bin/sing-box:ro
      - ./config.json:/etc/sing-box/config.json:ro
    restart: unless-stopped
